src/QuoteMyGoods/Models/Product.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteMyGoods.Models
{
    [JsonObject]
    public class Product
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Category { get; set; }
        public string Description { get; set; }
        [Required]
        public string ImgUrl { get; set; }
        [Required]
        public decimal Price { get; set; }
    }
}

src/QuoteMyGoods/Controllers/Products/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using QuoteMyGoods.Models;
using QuoteMyGoods.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;

namespace QuoteMyGoods.Controllers.Products
{
    [Authorize(Roles = "Pleb,Administrator")]
    public class ProductsController:Controller
    {
        private IQMGRepository _repository;
        private IBasketService _basketService;
        private ILoggingService _logger;
        private IRedisService _redisService;
        private UserManager<QMGUser> _userManager;

        public ProductsController(IQMGRepository repository, IBasketService basketService,ILoggingService logger,IRedisService redisService, UserManager<QMGUser> userManager)
        {
            _repository = repository;
            _basketService = basketService;
            _logger = logger;
            _redisService = redisService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Products(string orderbyList, string categoryList, int? itemsPerPage, int? pageNumber)
        {
            _logger.Log(_userManager.GetUserId(HttpContext.User), "GetProducts");
            IEnumerable<Product> products = await _repository.GetProductsByCategory(categoryList);

            if (string.IsNullOrWhiteSpace(itemsPerPage.ToString()))
            {
                itemsPerPage = HttpContext.Session.GetInt32("itemsPerPage") ?? 6;
            }

            if (string.IsNullOrWhiteSpace(pageNumber.ToString()))
            {
                pageNumber = HttpContext.Session.GetInt32("pageNumber") ?? 1;
                if (pageNumber > (products.Count() / itemsPerPage))
                {
                    pageNumber = 1;
                }
            }

            AddInfoToSession((int)itemsPerPage, (int)pageNumber);

            ViewData["categoryList"] = await _repository.GetCategories();

            ViewData["orderbyList"] = new SelectList(new List<string>() { "Name", "Price low-to-high", "Price high-to-low", "Category" });

            if (!string.IsNullOrEmpty(orderbyList))
            {
                products = _OrderBy(products, orderbyList);
            }

            var pagedProducts = products.Skip(((int)pageNumber - 1) * (int)itemsPerPage).Take((int)itemsPerPage);

            //_redisService.SetObject("Products", pagedProducts);
            //var t = _redisService.GetObject<IEnumerable<Product>>("Products");

            return View(pagedProducts);
        }

        private void AddInfoToSession(int itemsPerPage, int pageNumber)
        {
            _logger.Log(_userManager.GetUserId(HttpContext.User), "AddInfoToSession");
            HttpContext.Session.SetInt32("itemsPerPage", itemsPerPage);
            HttpContext.Session.SetInt32("pageNumber", pageNumber);
        }

        private IEnumerable<Product> _OrderBy(IEnumerable<Product> products,string _string)
        {
            switch (_string)
            {
                case "Name":
                    products = products.OrderBy(p => p.Name);
                    break;
                case "Price low-to-high":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "Price high-to-low":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                case "Category":
                    products = products.OrderBy(p => p.Category);
                    break;
                default:
                    break;
            }
            return products;
        }

        public async Task<IActionResult> Details(int? id)
        {
            _logger.Log(_userManager.GetUserId(HttpContext.User), "GetProductDetails");
            if (id == null)
            {
                return NotFound();
            }

            var product = await _repository.GetProductById(id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            _logger.Log(_userManager.GetUserId(HttpContext.User), "DeleteProducts");
            if (id == null)
            {
                return NotFound();
            }

            Product product = await _repository.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            _logger.Log(_userManager.GetUserId(HttpContext.User), "DeleteProductsConfirmed");
            _repository.DeleteProduct(id);
            _repository.SaveAll();
            return RedirectToAction("Products");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product product)
        {
            _logger.Log(_userManager.GetUserId(HttpContext.User), "CreateProduct");
            if (ModelState.IsValid)
            {
                _repository.AddProduct(product);
                _repository.SaveAll();
                return RedirectToAction("Products");
            }
            return View(product);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            _logger.Log(_userManager.GetUserId(HttpContext.User), "GetEditProduct");
            if (id == null)
            {
                return NotFound();
            }

            Product product = await _repository.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            _logger.Log(_userManager.GetUserId(HttpContext.User), "EditProduct");
            if (ModelState.IsValid)
            {
                _repository.UpdateProduct(product);
                _repository.SaveAll();
                return RedirectToAction("Products");
            }
            return View(product);
        }
    }
}

src/QuoteMyGoods/ViewComponents/CreateModalViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteMyGoods.ViewComponents
{
    public class CreateModalViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

src/QuoteMyGoods/ViewComponents/PagingViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using QuoteMyGoods.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteMyGoods.ViewComponents
{
    public class PagingViewComponent:ViewComponent
    {
        private readonly IQMGRepository _repository;

        public PagingViewComponent(IQMGRepository repository)
        {
            _repository = repository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var itemsPerPage = HttpContext.Request.Query["itemsPerPage"];

            if (!string.IsNullOrWhiteSpace(itemsPerPage))
            {
                ViewBag.itemsPerPage = int.Parse(itemsPerPage);
            }
            else
            {
                ViewBag.itemsPerPage = HttpContext.Session.GetInt32("itemsPerPage") ?? 6;
            }

            var pageNumber = HttpContext.Request.Query["pageNumber"];

            if (!string.IsNullOrWhiteSpace(pageNumber))
            {
                ViewBag.pageNumber = int.Parse(pageNumber);
            }
            else
            {
                ViewBag.pageNumber = HttpContext.Session.GetInt32("pageNumber") ?? 1;
            }

            ViewBag.productCount = _repository.CurrentProductCount();
            return View();
        }
    }
}

src/QuoteMyGoods/ViewComponents/ProductDeleteViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QuoteMyGoods.Models;
using System.Threading.Tasks;

namespace QuoteMyGoods.ViewComponents
{

    public class ProductDeleteViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(Product product)
        {
            return View(product);
        }
    }
}

src/QuoteMyGoods/ViewComponents/ProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QuoteMyGoods.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteMyGoods.ViewComponents
{
    public class ProductViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(Product product)
        {
            return View(product);
        }
    }
}

src/QuoteMyGoods/Views/Products/Create.cshtml
@model QuoteMyGoods.Models.Product

@{ 
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<form asp-controller="Products" asp-action="Create" method="post">
    <div class="form-horizontal">
        <h4>Product</h4>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Category" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Price" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ImgUrl" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Products">Back to products</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/QuoteMyGoods/Views/Products/Delete.cshtml
@model QuoteMyGoods.Models.Product

@{ 
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>

<div class="row">
    <div>@await Component.InvokeAsync("ProductDelete",new { product = Model })</div>
</div>

<form asp-controller="Products" asp-action="DeleteConfirmed" asp-route-id="@Model.Id" method="post">
    <div class="form-actions">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Products">Back to List</a>
    </div>
</form>

<br />
<br />

src/QuoteMyGoods/Views/Products/Details.cshtml
@model QuoteMyGoods.Models.Product

@{ 
    ViewBag.Title = Model.Name;
}

<div>
    @await Component.InvokeAsync("ProductDetails", new { product = Model })
</div>

src/QuoteMyGoods/Views/Products/Edit.cshtml
@model QuoteMyGoods.Models.Product

@{ 
    ViewBag.Title = "Update";
}

<form asp-action="Edit" method="post">
    <div class="form-horizontal">
        <h4>@Model.Name</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />

        <div class="form-group">
            <label asp-for="Name" class="col-md-4 control-label"></label>
            <div class="col-md-8">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Category" class="col-md-4 control-label"></label>
            <div class="col-md-8">
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="col-md-4 control-label"></label>
            <div class="col-md-8">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Price" class="col-md-4 control-label"></label>
            <div class="col-md-8">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="ImgUrl" class="col-md-4 control-label"></label>
            <div class="col-md-8">
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-8">
                <input type="submit" value="Save" class="btn btn-success"/>
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Details" asp-route-id="@Model.Id">Back to product</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/QuoteMyGoods/Views/Products/Products.cshtml
@model IEnumerable<QuoteMyGoods.Models.Product>

@{
    ViewBag.Title = "Products";
    var itemsPerRow = 6;
}

<button id="hideFilters" class="btn btn-success"><i class="fa fa-chevron-up"></i></button>

<hr />

<div id="filters">
    <div class="row">
        @if (User.IsInRole("Administrator"))
        {
            <div class="col-md-5">
                <a asp-action="Create" class="btn btn-primary">Create new</a>
            </div>
        }
        <div class="col-md-5">
            <button type="button" class="btn btn-info" data-toggle="modal" data-target="#createModal">Create with jQuery</button>
        </div>
    </div>

    <br />

    <div class="row">
        <form asp-controller="Products" asp-action="Products" method="get">
            <div class="col-md-5">
                <div class="form-group">
                    <label for="orderbyList">Order by: </label>
                    @Html.DropDownList("orderbyList", "All")
                </div>
                <div class="form-group">
                    <label for="itemsPerPage">Select Category: </label>
                    @Html.DropDownList("categoryList", "All")
                </div>
                <div class="form-group">
                    <label>Items per page</label>
                    <select id="itemsPerPage" name="itemsPerPage">
                        <option value="6">6</option>
                        <option value="12">12</option>
                        <option value="18">18</option>
                        <option value="24">24</option>
                    </select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Filter" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
    <hr />
</div>

<div class="row">
    @await Component.InvokeAsync("Paging")
</div>

<div>
    @{
        int lim = itemsPerRow;
    }
    @for (int i = 0; i < Model.Count(); i += itemsPerRow)
    {
        <div class="row row-eq-height">
            @for (int j = i; j < lim && j < Model.Count(); j++)
            {
                @await Component.InvokeAsync("Product", new { product = Model.ElementAt(j) });

            }
            @{
                lim+=itemsPerRow;
            }
        </div>
    }
</div>

<div class="row">
    @await Component.InvokeAsync("Paging")
</div>

<div>
    @await Component.InvokeAsync("CreateModal")
</div>