src/QuoteMyGoods/Controllers/Basket/BasketController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using QuoteMyGoods.Common;
using QuoteMyGoods.Models;
using QuoteMyGoods.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace QuoteMyGoods.Controllers.Basket
{
    [Authorize]
    public class BasketController:Controller
    {
        IBasketService _basketService;
        IQMGRepository _repository;
        ILoggingService _logger;
        IBlobbingService _blobber;
        UserManager<QMGUser> _userManager;

        public BasketController(IBasketService basketService, IQMGRepository repository,ILoggingService logger, IBlobbingService blobber, UserManager<QMGUser> userManager)
        {
            _basketService = basketService;
            _repository = repository;
            _logger = logger;
            _blobber = blobber;
            _userManager = userManager;
        }
        
        public IActionResult Basket()
        {
            var basket = _basketService.GetBasket();
            ViewBag.TotalPrice = _basketService.GetTotalPrice();
            return View(basket);
        }

        [HttpPost]
        public async Task<IActionResult> AddToBasket(int? id, string orderbyList, string categoryList, string pageNumber, string itemsPerPage)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _repository.GetProductById(id);

            if (product == null)
            {
                return NotFound();
            }
            else
            {
                _basketService.AddToBasket(product);
                _logger.Log(_userManager.GetUserId(HttpContext.User), "AddToBasket");
                return RedirectToAction("Products", "Products", new { orderbyList = orderbyList, categoryList = categoryList, pageNumber = pageNumber, itemsPerPage = itemsPerPage });
            }
        }

        [HttpPost]
        public IActionResult RemoveFromBasket(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                _basketService.RemoveFromBasket((int)id);
                _logger.Log(_userManager.GetUserId(HttpContext.User), "RemoveFromBakset");
                return RedirectToAction("Basket");
            }
        }

        [HttpPost]
        public IActionResult AddQuantity(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            else
            {
                _basketService.AddQuantity((int)id);
                _logger.Log(_userManager.GetUserId(HttpContext.User), "AddQuantity");
                return RedirectToAction("Basket");
            }
        }

        [HttpPost]
        public IActionResult MinusQuantity(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            else
            {
                _basketService.MinusQuantity((int)id);
                _logger.Log(_userManager.GetUserId(HttpContext.User), "MinusQuantity");
                return RedirectToAction("Basket");
            }
        }

        [HttpPost]
        public IActionResult ClearBasket()
        {
            _basketService.ClearBasket();
            _logger.Log(_userManager.GetUserId(HttpContext.User), "ClearBasket");
            return RedirectToAction("Basket");
        }

        [HttpPost]
        public IActionResult SaveBasket()
        {
            var reference = _userManager.GetUserId(HttpContext.User) + "basketBlob";
            _blobber.UploadBlob(reference, _basketService.GetBasket());
            return RedirectToAction("Basket");
        }

        [HttpPost]
        public IActionResult LoadBasket()
        {
            var reference = _userManager.GetUserId(HttpContext.User) + "basketBlob";
            _basketService.SetBasket(_blobber.GetBlob<Dictionary<int, BasketItem>>(reference));
            return RedirectToAction("Basket");
        }
    }
}

src/QuoteMyGoods/ViewComponents/BasketItemViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QuoteMyGoods.Common;
using QuoteMyGoods.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteMyGoods.ViewComponents
{
    public class BasketItemViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(BasketItem basketItem)
        {
            return View(basketItem);
        }
    }
}

src/QuoteMyGoods/Views/Basket/Basket.cshtml
@model IDictionary<int, QuoteMyGoods.Common.BasketItem>

@{
    ViewBag.Title = "Basket";
}

<div class="col-md-8 col-md-offset-2">
    @if (ViewBag.TotalPrice == 0)
    {
        <div class="well">
            Your basket is empty!
        </div>
        <div class="col-md-1">
            <form asp-controller="Basket" asp-action="SaveBasket" method="post">
                <button type="submit" class="btn btn-danger">Save basket</button>
            </form>
        </div>
        <div class="col-md-1">
            <form asp-controller="Basket" asp-action="LoadBasket" method="post">
                <button type="submit" class="btn btn-danger">Load basket</button>
            </form>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-md-3 text-left">
                Name
            </div>
            <div class="col-md-3 text-left">
                Category
            </div>
            <div class="col-md-2 text-left">
                Price
            </div>
            <div class="col-md-2 text-left">
                Quantity
            </div>
            <div class="col-md-2 text-left">
            </div>
        </div>
        <hr />
        <div class="row">
            @foreach (var item in Model.Values)
            {
                <div>@await Component.InvokeAsync("BasketItem", new { basketItem = item })</div>
            }
        </div>
        <hr />
        <div class="row">
            <div class="col-md-3">
                <a asp-controller="Products" asp-action="Products">Go back to products page.</a>
            </div>
            <div class="col-md-3 col-md-offset-5">
                Total price:£@ViewBag.TotalPrice
                <button class="btn btn-success">Checkout</button>
            </div>
            <div class="col-md-1">
                <form asp-controller="Basket" asp-action="ClearBasket" method="post">
                    <button type="submit" class="btn btn-danger">Clear basket</button>
                </form>
            </div>
            <div class="col-md-1">
                <form asp-controller="Basket" asp-action="SaveBasket" method="post">
                    <button type="submit" class="btn btn-danger">Save basket</button>
                </form>
            </div>
            <div class="col-md-1">
                <form asp-controller="Basket" asp-action="LoadBasket" method="post">
                    <button type="submit" class="btn btn-danger">Load basket</button>
                </form>
            </div>
        </div>
    }
    </div>