src/QuoteMyGoods/Controllers/Admin/AdminController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using QuoteMyGoods.Models;
using QuoteMyGoods.Services;
using System;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace QuoteMyGoods.Controllers.Admin
{
    public class LoggingDocument
    {
        public string id { get; set; }
        public string UserId { get; set; }
        public string Process { get; set; }
        public DateTime Time { get; set; }

        public LoggingDocument(string userId, string process)
        {
            UserId = userId;
            Process = process;
            Time = DateTime.Now.ToUniversalTime();
        }
    }

    public class AdminController : Controller
    {
        //private MyDocumentDB _db;
        private IQMGRepository _repository;
        private ITableService _tableService;

        public AdminController(IQMGRepository repo, ITableService tableService)
        {
           // _db = new MyDocumentDB(/*"alexpscdb",Startup.Configuration["DocumentDB:ConnectionUri"],Startup.Configuration["DocumentDB:PrimaryKey"]*/);
            _repository = repo;
            _tableService = tableService;
        } 
        // GET: /<controller>/
        public IActionResult Index(string userId)
        {
            /*
            IEnumerable<LoggingDocument> logs =  _db.GetAllDocs("logging") ?? Enumerable.Empty<LoggingDocument>();

            ViewData["userId"] = new SelectList(logs.Select(l => l.UserId).Distinct());

            if (!string.IsNullOrWhiteSpace(userId))
            {
                logs = _db.GetDocsByUserId("logging", userId);
            }
            */
            var logs = Enumerable.Empty<LoggingDocument>();

            return View(logs);
        }

        public IActionResult Details(string id)
        {
            //var log = _db.GetDocById("logging",id);
            var log = default(LoggingDocument);
            return View(log);
        }

        public IActionResult Tables(string partition, string entityType)
        {
            /*
            switch (entityType){
                case "user":
                    IEnumerable<UserEntity> userTables = _tableService.GetTables(partition, new UserEntity().entityResolver) ?? Enumerable.Empty<UserEntity>();
                    return View(userTables);
                default:
                    IEnumerable<ProductEntity> productTables = _tableService.GetTables(partition, new ProductEntity().entityResolver) ?? Enumerable.Empty<ProductEntity>();
                    return View(productTables);
            }
            */
            return View();
        }
    }
}

src/QuoteMyGoods/Controllers/App/AppController.cs
using Microsoft.AspNetCore.Mvc;
using QuoteMyGoods.Services;
using QuoteMyGoods.ViewModels;
using QuoteMyGoods.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace QuoteMyGoods.Controllers.App
{
    public class AppController : Controller
    {
        private IMailService _mailService;

        public AppController(IMailService service)
        {
            _mailService = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                var email = Startup.Configuration["AppSettings:SiteEmailAddress"];

                if (string.IsNullOrWhiteSpace(email))
                {
                    ModelState.AddModelError("", "Could not send email, configuration problem.");
                }

                if (_mailService.SendMail(email,
                  email,
                  $"Contact Page from {model.Name} ({model.Email})",
                  model.Message))
                {
                    ModelState.Clear();

                    ViewBag.Message = "Mail Sent. Thanks!";

                }
            }

            return View();
        }
    }
}

src/QuoteMyGoods/ViewComponents/BasketCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QuoteMyGoods.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuoteMyGoods.ViewComponents
{
    public class BasketCountViewComponent:ViewComponent
    {
        private IBasketService _basketService;

        public BasketCountViewComponent(IBasketService basketService)
        {
            _basketService = basketService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewBag.Count = _basketService.GetBasketCount();
            return View();
        }
    }
}

src/QuoteMyGoods/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/lib/angular/angular.js"></script>
    <script src="//d3js.org/d3.v3.min.js" charset="utf-8"></script>

    @RenderSection("Scripts", false)
</head>
<body>
    <div>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="App" asp-action="Index" class="navbar-brand">Quote My Goods</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="App" asp-action="Index">Home</a></li>
                        <li><a asp-controller="App" asp-action="About">About</a></li>
                        <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
                        <li><a asp-controller="Admin" asp-action="Index">Admin</a></li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li><a asp-controller="Auth" asp-action="Login">Login</a></li>
                            <li><a asp-controller="Auth" asp-action="Signup">Signup</a></li>

                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><a asp-controller="Products" asp-action="Products">Products</a></li>
                            <li><a asp-controller="Auth" asp-action="Logout">Logout</a></li>
                        }
                    </ul>
                    <ul class="nav navbar-right">
                        <li>@await Component.InvokeAsync("BasketCount")</li>
                    </ul> 
                </div>
            </div>
        </nav>
        <div id="main" class="container-fluid">
            <div>
                @RenderBody()
            </div>
        </div>
        <br />
        <br />
        <div id="footer" class="container-fluid">
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <h4 class="text-center text-info">&copy; 2015 Quote My Goods Ltd.</h4>
            </div>
        </div>
    </div>

    <script>
    $(document).ready(function () {
        $("#hideFilters").on("click", function () {
            $("#hideFilters i").toggleClass("fa-chevron-down").toggleClass("fa-chevron-up");
            $("#filters").toggle("slow");
        });        
    });
    </script>

</body>
</html>